start_date: "2024-04-01_02:00:00"  # Start date of the data processing
end_date: "2024-07-30_00:00:00"
interval_hours: "1"                # Interval for processing (e.g., hourly, 6-hourly)

average: 
scale: 1

significance: True
ci: True


plot_type: line

unique:

fcst_var:

legend_style: True

vars:

  - observed_diff: "./T2M_sign-ens_0.data"
  - observed_diff: "./T2M_sign-ens_1.data"
  - observed_diff: "./T2M_sign-ens_2.data"
  - observed_diff: "./T2M_sign-ens_3.data"
# General plot parameters
plot_title: "Temperature at 2m - (EnKF - blending)"
legend_title: "Model"
labels:
  - "ens_0"
  - "ens_1"
  - "ens_2"
  - "ens_3"

line_color:
  - "red"
  - "green"
  - "orange"
  - "blue"

line_marker:
  - "x"
  - "x"
  - "x"
  - "x"

line_type:
  - "-."
  - "-."
  - "-."
  - "-."

line_width:
  - 1
  - 1
  - 1
  - 1

output_filename: ens-sig_T2M.png

# Line plot variables
x_label: "Lead Time"
y_label: "RMSE"
ylim: [-0.5,0.5]
xlim: [0,36]        # Adjust as needed for your dataset
grid: true
yticks:  # Customize tick marks if needed
xticks: [0,3,6,9,12,15,18,21,24,27,30,33,36]       # Customize tick marks if needed
