start_date: "2024-04-01_02:00:00"  # Start date of the data processing
end_date: "2024-04-07_17:00:00"    # End date of the data processing
interval_hours: "1"            # Interval for processing (e.g., hourly, 6-hourly)

fcst_file_template: "/scratch2/BMC/fv3lam/Vanderlei.Vargas/verification_AIML/next/rmse/links/proc_graphhrrr_{year}-{month}-{day}T{hour}:00:00.nc"  # Forecast file template
fcst_var: "T2M"                                       # Forecast variable name

ref_file_template: "/scratch2/BMC/fv3lam/Vanderlei.Vargas/verification_AIML/obs/{year}{month}{day}/{cycle}/hrrr.t{hour}z.wrfprsf00.grib2"     # Reference file template
ref_var: "t"                                      # Reference variable name

output_dir: "/scratch2/BMC/fv3lam/Vanderlei.Vargas/verification_AIML/next/rmse"                                   # Directory to save outputs
output_filename: "stat.txt"            # Output file template

stat_name:                                              # Statistical metric to calculate 
- "rmse"
- "bias"
- "quantiles"
- "mae"
target_grid: "fcst"                                     # Target grid specification

processes: 100
