plot_type: performance_diagram
var_name: RMSE
plot_title: Performance Diagram
legend_title: Model
input_files:
- "/path/to/file_test_1.txt"
- "/path/to/file_test_2.txt"
labels:
- "Model 1"
- "Model 2"
line_color:
- "blue"
- "green"
line_marker:
- "d"
- "o"
line_type:
- "-"
- "-."
line_width:
- 1
- 1
output_filename: output.png
