# ====================================================
# MET Stat Configuration File
# ====================================================
# This YAML configuration file is used to run the MET stat mode.
# It defines the paths, filtering criteria, and output options for processing
# .stat files with meteorological statistical data.

# ------------------------
# Input and Line Type Settings
# ------------------------
input_stat_folder: /path/to/MET/stats     # Folder containing the input .stat files
line_type: cts                            # Line type to filter records (e.g., cnt, cts, ecnt...)

# ------------------------
# Date Settings
# ------------------------
date_column: fcst_valid_beg               # The column name to use for date filtering (e.g., fcst_valid_beg)
start_date: "2022-05-01_00:00:00"           # Start date/time for data processing
end_date: "2022-05-08_00:00:00"             # End date/time for data processing

# ------------------------
# Filtering Options
# ------------------------
# Threshold filtering: Define minimum and maximum values for specific columns.
thresholds:  
  rmse: [1, 2]                          # Filter rows with rmse value between 1 and 2

# String filtering: Allow only specified string values for given columns.
string_filters:  
  model: ["RRFS_GDAS_GF.SPP.SPPT_mem01","RRFS_GDAS_GF.SPP.SPPT_mem02"]  # Only include these models
  fcst_var: ["APCP_03"]                  # Only include this forecast variable
  fcst_thresh: [">0.0"]                  # Include only thresholds greater than 0.0
  fcst_lead: ['030000', '060000', '090000']  # Only include these forecast lead times

# Column filtering: Keep only the specified columns (leave empty to retain all columns)
columns_to_keep: ["fcst_valid_beg", "model", "fcst_thresh", "obs_thresh", "line_type"]

# ------------------------
# Output Options
# ------------------------
# Save the reformatted DataFrame to a file
reformat_file: true                      
output_reformat_file: "/path/to/filtered_output.data"  # File path for the full filtered data

# Extract specific metrics (statistical variables) to save
output_file: true                        
stat_vars: ["fbias", "gss"]              # List of selected metric names to output
output_plot_file: "/path/to/output.data" # File path for saving the output metrics data

# Aggregation Options
aggregate: true                          # Whether to perform data aggregation
group_by: ["fcst_lead"]                  # Columns to group by for aggregation (order matters)
output_agg_file: "/path/to/output_agg.data"  # File path for saving aggregated data
