start_date: "2024-04-01_02:00:00"  # Start date of the data processing
end_date: "2024-04-07_17:00:00"    # End date of the data processing
interval_hours: "1"                # Interval in hours for processing (e.g., 1, 6)

fcst_file_template: "/path/to/forecast/forecast_{year}-{month}-{day}T{hour}:00:00.nc"  # Forecast file template (netcdf or grib2)
fcst_var: "T2M"                               # Forecast variable name

ref_file_template: "/path/to/reference/obs_{year}{month}{day}/{cycle}/hrrr.t{hour}z.wrfprsf00.grib2" # Reference file template (netcdf or grib2)
ref_var: "t"                                  # Reference variable name

output_dir: "/path/to/output_dir"             # Directory to save output
output_filename: "output_file.txt"            # Output file template

stat_name:                                    # Statistical metric to calculate (rmse, bias, quantiles, mae)
- "rmse"
- "bias"
- "quantiles"
- "mae"
target_grid: "fcst"                            # Target grid

processes: 100                                 # number of parallel processes
