# Date and Time Settings
start_date: "2024-04-01_02:00:00"  # Start date of the data processing
end_date: "2024-04-07_17:00:00"    # End date of the data processing
interval_hours: "1"                # Interval in hours for processing (e.g., 1, 6)

# Forecast Configuration
fcst_file_template: "/path/to/forecast/forecast_{year}-{month}-{day}T{hour}:00:00.nc"  # Forecast file template (netcdf or grib2)
fcst_var: "T2M"                               # Forecast variable name
shift: -1                                     # Time shift (if any)

# Reference Configuration
ref_file_template: "/path/to/reference/obs_{year}{month}{day}/{cycle}/hrrr.t{hour}z.wrfprsf00.grib2" # Reference file template (netcdf or grib2)
ref_var: "t"                                  # Reference variable name

# Output Configuration
output_dir: "/path/to/output_dir"             # Directory to save output
output_filename: "output_file.txt"            # Output file template

# Statistical Metrics (rmse, bias, quantiles, mae, gss, fbias)
stat_name:                                    
- "rmse"
- "bias"
- "quantiles"
- "mae"
- "gss"

# Variable Threshold and Radius
var_threshold: 10                  # Threshold value for analysis
var_radius: 10                     # Influence radius for calculations (0 - None)

# Grid and Interpolation Settings
interpolation: false               # Whether to interpolate data
target_grid: "fcst"                # Target grid specification

# Parallel Processing
processes: 200                     # Number of processes to run in parallel