plot_type: line
vars:
- rmse: "../filtered_output.data"
- mae: "../filtered_output.data"

# General plot parameters
plot_title: T2M
legend_title: Stats
labels:
- "RMSE"
- "MAE"
line_color:
- "blue"
- "black"
line_marker:
- "d"
- "o"
line_type:
- "-"
- "-."
line_width:
- 1
- 1
output_filename: output.png

# Line plot variables
x_label: "x"
y_label: "y"
ylim: [0,1.5]
xlim: [0,20]
grid: true
y_ticks: [0,0.5,1,1.5]

