# ====================================================
# Date and Time Settings
# ====================================================
# These settings define the time period and time intervals for data processing.
start_date: "2024-04-01_02:00:00"        # Starting date and time for processing
end_date: "2024-04-01_03:00:00"          # Ending date and time for processing
interval_hours: "1"                    # Time interval (in hours) at which processing is performed

# Additional settings to define forecast lead times.
start_lead_time: 0                     # Starting lead time (e.g., forecast offset in hours)
end_lead_time: 5                       # Ending lead time
interval_lead_time: 1                  # Lead time step (e.g., each 1 hour)

# Or
lead_times: [0,1,2]

members: ["ens_0", "ens_1"] # If set, it loops over all the ensemble members

# ====================================================
# Forecast Configuration
# ====================================================
# The forecast configuration defines the file template and variable settings for forecast data.
fcst_file_template: "/path/to/{year}{month}{day}/{members}/uppfiles/WRFPRS.GrbF{lead_time}.grib2"
  # Template used to locate forecast files.
fcst_var: "T2M"                         # Variable name in the forecast file (e.g., 2-meter temperature)
fcst_level: 2                           # Level (e.g., vertical level) for the forecast variable
fcst_type_of_level: "heightAboveGround" # Type of level for the forecast variable (used when processing grib2 files)

# ====================================================
# Reference Configuration
# ====================================================
# These settings define the file template and variable parameters for the reference (observational) data.
ref_file_template: "/path/to/{valid_year}{valid_month}{valid_day}/hrrr.t{valid_hour}z.wrfprsf00.grib2"
  # Template used to locate reference files.
ref_var: "T2M"                         # Variable name in the reference file
ref_level: 2                           # Level for the reference variable
ref_type_of_level: "heightAboveGround" # Type of level for the reference variable (used when processing grib2 files)

# ====================================================
# Output Configuration
# ====================================================
# Defines where the results will be saved.
output_dir: "."                        # Directory for saving the output files (current directory in this case)
output_filename: "output.data"         # File name for the output file

# ====================================================
# Statistical Metrics
# ====================================================
# Specify the type of statistical analysis and the metrics to be computed.
stat_type: "det"                      # Type of statistics to compute ("det" for deterministic,
                                      # "ens" would be for ensemble if applicable)
stat_name:                            # List of statistical metrics to calculate
  - "rmse"
  - "bias"
  - "fss:20:20:1"

# ====================================================
# Grid and Interpolation Settings
# ====================================================
# These settings control whether interpolation is applied and the target grid used for analysis.
interpolation: true                    # Boolean flag indicating whether interpolation should be performed
target_grid: "/path/to/domain_grid.nc"
  # The grid specification or file used as the target for interpolation

# ====================================================
# Parallel Processing
# ====================================================
# Controls the number of processes used to run the analysis in parallel.
processes: 1                           # The number of processes to run in parallel (set to 1 in this example)
