name: Run Core Tests

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository (including submodules)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0         
          submodules: recursive 
          # Disable persisted credentials so URLs are not rewritten to HTTPS.
          persist-credentials: false

      - name: Set up SSH
        run: |
          # Start the SSH agent.
          eval "$(ssh-agent -s)"
          # Add the SSH private key stored in GitHub Secrets (replace 'SSH_PRIVATE_KEY' with your secret name).
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          # Add GitHub's host key to known_hosts to avoid verification prompts.
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Update submodules to latest main branch
        run: |
          git submodule update --init --recursive --remote

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt

      - name: Run workflow tests
        run: |
          pytest -v --maxfail=5 --disable-warnings

