name: Run Core Tests

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository (including submodules)
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0  

      - name: Update submodules to latest main branch
        run: |
          git submodule update --init --recursive --remote

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover tests

